[package]
name = "atm0s-sdn-transport-tcp"
version = "0.1.2"
edition = "2021"
description = "TCP Transport in atm0s-sdn"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atm0s-sdn-network = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
atm0s-sdn-identity = { workspace = true }
bincode = { workspace = true }
async-std = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
atm0s-sdn-utils = { workspace = true }
futures-util = "0.3"
async-bincode = { version = "0.7.2", features = ["futures"], default-features = false }
