[package]
name = "atm0s-sdn-standalone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = "0.3.17"
log.workspace = true
clap.workspace = true
serde.workspace = true
atm0s-sdn = { path = "../packages/runner", version = "0.1.10", features = ["vpn"] }
tokio = { version = "1.36.0", features = ["full"] }
poem = { version = "2.0", features = ["embed", "static-files", "websocket"] }
rust-embed = { version = "8.2", optional = true }

futures-util = "0.3.30"
tracing-subscriber = "0.3.18"
serde_json = "1.0.116"

[features]
default = ["embed"]
embed = ["rust-embed"]