[package]
name = "atm0s-sdn-tun-tap"
version = "0.1.0"
edition = "2021"
description = "Tun/Tap service in atm0s-sdn"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
async-trait = { workspace = true }
atm0s-sdn-identity = { workspace = true }
atm0s-sdn-router = { workspace = true }
atm0s-sdn-utils = { workspace = true }
atm0s-sdn-network = { workspace = true }
async-std = { workspace = true }
futures = "0.3"
tun = { git = "https://github.com/giangndm-bluesea/rust-tun.git", hash = "d05f882cab35373e26016867f4ed100158b759c7" }
parking_lot = { workspace = true }