[package]
name = "tun-tap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
async-trait = { workspace = true }
bluesea-identity = { workspace = true }
bluesea-router = { workspace = true }
utils = { workspace = true }
network = { workspace = true }
async-std = { workspace = true }
futures = "0.3"
tun = { git = "https://github.com/giangndm-bluesea/rust-tun.git", hash = "d05f882cab35373e26016867f4ed100158b759c7" }
parking_lot = { workspace = true }