[package]
name = "atm0s-sdn-layers-spread-router"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atm0s-sdn-identity = { workspace = true }
atm0s-sdn-router = { workspace = true }
atm0s-sdn-utils = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }


[dev-dependencies]
env_logger = { workspace = true }
criterion = { version = "0.5.1" }
rand = { version = "0.8.5" }

[[bench]]
name = "router"
harness = false