[package]
name = "atm0s-sdn-transport-udp"
version = "0.1.0"
edition = "2021"
description = "UDP Transport in atm0s-sdn"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atm0s-sdn-network = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
atm0s-sdn-identity = { workspace = true }
async-std = { workspace = true }
log = { workspace = true }
atm0s-sdn-utils = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
futures-util = "0.3"
async-notify = { workspace = true }
socket2 = "0.5.5"
