[package]
name = "atm0s-sdn-transport-compose"
version = "0.1.1"
edition = "2021"
description = "UDP Transport in atm0s-sdn"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
