[package]
name = "atm0s-sdn-rpc"
version = "0.1.0"
edition = "2021"
description = "RPC service in atm0s-sdn"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atm0s-sdn-identity = { path = "../../core/identity", version = "0.1.1" }
atm0s-sdn-router = { path = "../../core/router", version = "0.1.1" }
atm0s-sdn-utils = { path = "../../core/utils", version = "0.1.1" }
atm0s-sdn-network = { path = "../../network", version = "0.2.0" }
parking_lot = { workspace = true }
async-std = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
bincode = { workspace = true }
