[package]
name = "atm0s-sdn-manual-discovery"
version = "0.1.0"
edition = "2021"
description = "Manual discovery service in atm0s-sdn"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
atm0s-sdn-identity = { workspace = true }
atm0s-sdn-utils = { workspace = true }
atm0s-sdn-network = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
async-std = { workspace = true }
env_logger = { workspace = true }
atm0s-sdn-layers-spread-router = { workspace = true }
atm0s-sdn-layers-spread-router-sync = { workspace = true }
atm0s-sdn-transport-vnet = { workspace = true }
atm0s-sdn-transport-tcp = { workspace = true }
clap = { workspace = true }
rand = { workspace = true }