[package]
name = "atm0s-sdn-layers-spread-router-sync"
version = "0.1.0"
edition = "2021"
description = "Spread router sync service in atm0s-sdn"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
bincode = { workspace = true }
atm0s-sdn-identity = { workspace = true }
atm0s-sdn-router = { workspace = true }
atm0s-sdn-utils = { workspace = true }
atm0s-sdn-network = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
atm0s-sdn-layers-spread-router = { workspace = true }
serde = { workspace = true }