[package]
name = "atm0s-sdn-key-value"
version = "0.1.5"
edition = "2021"
description = "KeyValue service for atm0s-sdn"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atm0s-sdn-identity = { path = "../../core/identity", version = "0.1.2" }
atm0s-sdn-router = { path = "../../core/router", version = "0.1.3" }
atm0s-sdn-utils = { path = "../../core/utils", version = "0.1.1" }
atm0s-sdn-network = { path = "../../network", version = "0.2.2" }
thiserror = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
async-std = { workspace = true }
parking_lot = { workspace = true }
mockall = { workspace = true }
small-map = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
allocation-counter = { workspace = true }
atm0s-sdn-utils = { path = "../../core/utils", version = "0.1.1", features = ["auto-clear"] }
