[package]
name = "atm0s-sdn-key-value"
version = "0.1.0"
edition = "2021"
description = "KeyValue service for atm0s-sdn"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atm0s-sdn-identity = { workspace = true }
atm0s-sdn-router = { workspace = true }
atm0s-sdn-utils = { workspace = true }
atm0s-sdn-network = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
async-std = { workspace = true }
parking_lot = { workspace = true }
mockall = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
allocation-counter = { workspace = true }
atm0s-sdn-utils = { workspace = true, features = ["auto-clear"] }