[package]
name = "atm0s-sdn-utils"
version = "0.2.1"
edition = "2021"
description = "A collection of utilities for atm0s-sdn"
license = "MIT"

[features]
auto-clear = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
serde = { workspace = true }
