[package]
name = "atm0s-sdn-transport-vnet"
version = "0.1.2"
edition = "2021"
description = "Vitual Network Transport in atm0s-sdn"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atm0s-sdn-network = { path = "../../network", version = "0.2.0" }
atm0s-sdn-identity = { path = "../../core/identity", version = "0.1.1" }
atm0s-sdn-utils = { path = "../../core/utils", version = "0.1.1" }
async-trait = { workspace = true }
parking_lot = { workspace = true }
async-std = { workspace = true }

[dev-dependencies]
atm0s-sdn-router = { path = "../../core/router", version = "0.1.1" }
bincode = { workspace = true }
serde = { workspace = true }
