[package]
name = "atm0s-sdn-router"
version = "0.1.1"
edition = "2021"
description = "Router interface for atm0s-sdn"
license = "MIT"

[features]
mock = ["mockall"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atm0s-sdn-identity = { path = "../identity", version = "0.1.1" }
mockall = { workspace = true, optional = true }
