[package]
name = "atm0s-sdn-integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
atm0s-sdn = { workspace = true, features = ["all"] }
atm0s-sdn-transport-vnet = { workspace = true }
bytes = "1.5.0"
log = "0.4.20"
env_logger = "0.10.1"
allocation-counter = { workspace = true }
async-std = { workspace = true }